version: '3'

services: 
    app:
        build: .
        container_name: app
        entrypoint: dockerize -template ./.docker/app/nginx.tmpl:./.docker/nginx/nginx.conf -wait tcp://db:3306 -timeout 20s ./.docker/entrypoint.sh
        volumes: 
            - .:/var/www
        depends_on: 
            - db
            - redis
        networks: 
            - app_network
        environment: 
            - NGINX_PORT_FPM=9000
            - NGINX_PORT=80
    nginx: 
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
        networks: 
            - app_network
        depends_on: 
            - app

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks: 
            - app_network
    redis:
        image: redis:alpine
        expose: 
            - 6379
        networks: 
            - app_network

networks: 
    app_network:
        driver: bridge